const fs = require("fs");
const path = require("path");

const backendUrl = process.env.BACKEND_URL || "http://127.0.0.1:8000";
const outPath = path.join(__dirname, "..", "milestone2", "config.js");

const banner = "// Auto-generated by scripts/build-config.js\n";
const body = `window.BACKEND_URL = "${backendUrl}";\n`;

fs.writeFileSync(outPath, banner + body, "utf-8");
console.log(`config.js written to ${outPath} with BACKEND_URL=${backendUrl}`);
